services:
  node_a:
    build: .
    environment:
      - NODE_ID=A
      - ALL_PEERS=A,B,C,D
    ports:
      - "8000:8000"

  node_b:
    build: .
    environment:
      - NODE_ID=B
      - ALL_PEERS=A,B,C,D
    ports:
      - "8001:8000"

  node_c:
    build: .
    environment:
      - NODE_ID=C
      - ALL_PEERS=A,B,C,D
    ports:
      - "8002:8000"

  node_d:
    build: .
    environment:
      - NODE_ID=D
      - ALL_PEERS=A,B,C,D
    ports:
      - "8003:8000"