# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gossip.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'gossip.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgossip.proto\"b\n\rGossipMessage\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0e\n\x06sender\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\x12\x0e\n\x06msg_id\x18\x05 \x01(\t\"+\n\x08SeenMsgs\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07msg_ids\x18\x02 \x03(\t\"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32U\n\rGossipService\x12#\n\x0bSendMessage\x12\x0e.GossipMessage\x1a\x04.Ack\x12\x1f\n\x0cSyncSeenMsgs\x12\t.SeenMsgs\x1a\x04.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gossip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GOSSIPMESSAGE']._serialized_start=16
  _globals['_GOSSIPMESSAGE']._serialized_end=114
  _globals['_SEENMSGS']._serialized_start=116
  _globals['_SEENMSGS']._serialized_end=159
  _globals['_ACK']._serialized_start=161
  _globals['_ACK']._serialized_end=183
  _globals['_GOSSIPSERVICE']._serialized_start=185
  _globals['_GOSSIPSERVICE']._serialized_end=270
# @@protoc_insertion_point(module_scope)
